export const config = { runtime: "edge" };

const FONT = "Consolas, Menlo, 'DejaVu Sans Mono', 'Courier New', monospace";
const withAccessibleText = (svg, c) => svg.replace(new RegExp(`(<text\\b[^>]*?)fill="${c.accent}"`, "g"), `$1fill="${c.accentText}"`);
const withOriginalFrame = (svg, c, mobile) => {
  const frame = mobile
    ? `<rect width="3" height="238" fill="${c.accent}" opacity=".7"/><path d="M0 .5H360M359.5 0V238M0 237.5H360" stroke="${c.border}" stroke-width="1" fill="none"/>`
    : `<rect width="3" height="196" fill="${c.accent}" opacity=".7"/><path d="M0 .5H900M899.5 0V196M0 195.5H900" stroke="${c.border}" stroke-width="1" fill="none"/>`;
  const closingTag = mobile ? "</svg>" : "</g></svg>";
  return svg.replace(closingTag, `${frame}${closingTag}`);
};

function mobileSvg(c, lines) {
  const W = 360;
  const H = 238;
  const lineSvg = lines.map((line, index) => `<text class="animated-prompt" x="36" y="218" font-family="${FONT}" font-size="10.5" font-weight="600" fill="${c.accent}" opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="0;${(index / lines.length).toFixed(3)};${(index / lines.length + .025).toFixed(3)};${((index + 1) / lines.length - .025).toFixed(3)};${((index + 1) / lines.length).toFixed(3)};1" dur="12s" repeatCount="indefinite"/>${line}</text>`).join("");
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" role="img" aria-labelledby="title desc"><title id="title">JOEYCH terminal-style profile card</title><desc id="desc">Mobile-friendly embedded systems profile and technical focus.</desc><defs><linearGradient id="bar" x1="0" x2="1"><stop stop-color="${c.bar}"/><stop offset="1" stop-color="${c.bg}"/></linearGradient><linearGradient id="prompt" y2="1"><stop stop-color="${c.bar}" stop-opacity=".6"/><stop offset="1" stop-color="${c.bar}" stop-opacity=".9"/></linearGradient></defs><style>@media (prefers-reduced-motion: reduce){.animated-prompt{display:none}.prompt{opacity:1}.prompt-cursor animate{display:none}}</style><rect width="${W}" height="${H}" rx="8" fill="${c.bg}"/><rect width="${W}" height="34" fill="url(#bar)"/><path d="M0 33.5H360" stroke="${c.border}" stroke-width=".5"/><circle cx="20" cy="17" r="4" fill="#ff5f57"/><circle cx="34" cy="17" r="4" fill="#febc2e"/><circle cx="48" cy="17" r="4" fill="#28c840"/><text x="64" y="21" font-family="${FONT}" font-size="10" font-weight="600" fill="${c.dim}">~/joeych - zsh</text><text x="20" y="81" font-family="${FONT}" font-size="28" font-weight="900" fill="${c.text}">JOEYCH</text><rect x="20" y="87" width="112" height="2" rx="1" fill="${c.accent}" opacity=".35"/><text x="20" y="113" font-family="${FONT}" font-size="13" fill="${c.muted}">Embedded systems · SuZhou · UTC+8</text><text x="20" y="136" font-family="${FONT}" font-size="12" fill="${c.muted}">Primary language · C</text><rect x="20" y="151" width="142" height="22" rx="11" fill="${c.soft}"/><circle cx="33" cy="162" r="3.5" fill="${c.accent}"/><text x="45" y="165.5" font-family="${FONT}" font-size="10" font-weight="700" fill="${c.accent}">EMBEDDED FOCUS</text><rect y="196" width="${W}" height="42" fill="url(#prompt)"/><path d="M0 195.5H360" stroke="${c.border}" stroke-width=".5"/><rect class="prompt-cursor" x="20" y="208" width="7" height="11" rx="1" fill="${c.accent}"><animate attributeName="opacity" values=".85;.1;.85" dur="1.1s" repeatCount="indefinite"/></rect><text class="prompt" x="36" y="218" font-family="${FONT}" font-size="10.5" font-weight="600" fill="${c.accent}" opacity="0">${lines[0]}</text>${lineSvg}</svg>`;
}

export default async function handler(req) {
  const url = new URL(req.url);
  const dark = url.searchParams.get("theme") !== "light";
  const mobile = url.searchParams.get("layout") === "mobile";
  const c = dark
    ? { bg: "#0a0c10", bar: "#12151b", text: "#e6edf3", muted: "#8b949e", dim: "#7d8590", border: "#30363d", accent: "#39d353", accentText: "#39d353", soft: "#0d2114" }
    : { bg: "#fcfbf9", bar: "#f5f2eb", text: "#1a1a1a", muted: "#57606a", dim: "#59636e", border: "#e5e1d8", accent: "#16a34a", accentText: "#137333", soft: "#dcfce7" };
  const lines = [">_Focus: Embedded Systems | C/C++ | Python", ">_Build: STM32 | Raspberry Pi Pico | PX4", ">_Explore: PCB Design | AI | Computer Vision"];
  if (mobile) return new Response(withOriginalFrame(withAccessibleText(mobileSvg(c, lines), c), c, true), { headers: { "Content-Type": "image/svg+xml", "Cache-Control": "public, max-age=0, must-revalidate" } });
  const lineSvg = lines.map((line, index) => `<text class="animated-prompt" x="44" y="177" font-family="${FONT}" font-size="12" font-weight="600" fill="${c.accent}" opacity="0"><animate attributeName="opacity" values="0;0;1;1;0;0" keyTimes="0;${(index / lines.length).toFixed(3)};${(index / lines.length + .025).toFixed(3)};${((index + 1) / lines.length - .025).toFixed(3)};${((index + 1) / lines.length).toFixed(3)};1" dur="12s" repeatCount="indefinite"/>${line}</text>`).join("");
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="196" viewBox="0 0 900 196" role="img" aria-labelledby="title desc"><title id="title">JOEYCH terminal-style GitHub profile card</title><desc id="desc">Embedded systems profile and technical focus.</desc><defs><clipPath id="clip"><rect width="900" height="196" rx="8"/></clipPath><linearGradient id="bar" x1="0" x2="1"><stop stop-color="${c.bar}"/><stop offset="1" stop-color="${c.bg}"/></linearGradient><linearGradient id="prompt" y2="1"><stop stop-color="${c.bar}" stop-opacity=".6"/><stop offset="1" stop-color="${c.bar}" stop-opacity=".9"/></linearGradient></defs><style>@media (prefers-reduced-motion: reduce){.animated-prompt{display:none}.prompt{opacity:1}.prompt-cursor animate{display:none}}</style><g clip-path="url(#clip)"><rect width="900" height="196" fill="${c.bg}"/><rect width="900" height="32" fill="url(#bar)"/><path d="M0 31.5H900" stroke="${c.border}" stroke-width=".5"/><circle cx="22" cy="16" r="4.5" fill="#ff5f57"/><circle cx="38" cy="16" r="4.5" fill="#febc2e"/><circle cx="54" cy="16" r="4.5" fill="#28c840"/><text x="74" y="20.5" font-family="${FONT}" font-size="11" font-weight="600" fill="${c.dim}" letter-spacing=".5">~/joeych - zsh</text><text x="28" y="80" font-family="${FONT}" font-size="34" font-weight="900" fill="${c.text}" letter-spacing="-.5">JOEYCH</text><rect x="28" y="85" width="128" height="2" rx="1" fill="${c.accent}" opacity=".35"/><text x="28" y="104" font-family="${FONT}" font-size="11" fill="${c.muted}" letter-spacing=".3">Embedded systems · SuZhou · UTC+8</text><rect x="28" y="116" width="126" height="20" rx="10" fill="${c.soft}"/><circle cx="41" cy="126" r="3.5" fill="${c.accent}"/><text x="53" y="129.5" font-family="${FONT}" font-size="9.5" font-weight="700" fill="${c.accent}" letter-spacing=".3">EMBEDDED FOCUS</text><rect y="156" width="900" height="40" fill="url(#prompt)"/><path d="M0 156H900" stroke="${c.border}" stroke-width=".5"/><rect class="prompt-cursor" x="28" y="168" width="7" height="11" rx="1" fill="${c.accent}"><animate attributeName="opacity" values=".85;.1;.85" dur="1.1s" repeatCount="indefinite"/></rect><text class="prompt" x="44" y="177" font-family="${FONT}" font-size="12" font-weight="600" fill="${c.accent}" opacity="0">${lines[0]}</text>${lineSvg}</g></svg>`;
  return new Response(withOriginalFrame(withAccessibleText(svg, c), c, false), { headers: { "Content-Type": "image/svg+xml", "Cache-Control": "public, max-age=0, must-revalidate" } });
}
